# docker-compose.yml(로컬용)
services:     # 컨테이너 지정

  web:
    container_name: web
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: golbang.settings
      REDIS_URL: redis://redis:6379/0  # Redis URL 환경 변수 설정
      REDIS_HOST: redis
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    container_name: db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:  # 포트포워딩 - 로컬의 호스트가 3306포트를 사용 중일 수 있으므로 3307 포트를 도커 컨테이너의 3306 포트로 포워딩해줌
      - "3307:3306"
    env_file: # 설정은 .env 파일에 의존
      - .env
    volumes:  # 파일 시스템 정의
      - dbdata:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports: # 포트포워딩 - 로컬의 호스트가 6379 포트를 사용 중일 수 있으므로 6379 포트를 도커 컨테이너의 6379 포트로 포워딩해줌
      - "6379:6379"
    volumes: # 파일 시스템 정의
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
