# docker-compose.yml(로컬용)
services:     # 컨테이너 지정

  web:
    container_name: web
    build: .  # . 은 디폴트 -> 프로젝트 내의 "Dockerfile"이라는 이름을 알아서 찾아 빌드해줌
    environment:
      DJANGO_SETTINGS_MODULE: golbang.settings
    restart: always
    volumes:  # 파일 시스템 정의
      - .:/app
    ports:
      - "8000:8000"
    env_file: #
      - .env

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:  # 포트포워딩 - 로컬의 호스트가 6379 포트를 사용 중일 수 있으므로 6379 포트를 도커 컨테이너의 6379 포트로 포워딩해줌
      - "6379:6379"
    volumes:  # 파일 시스템 정의
      - redisdata:/data

volumes:
  redisdata:

